spring:
  application:
    name: Bank-Card-Management-System

  # DB
  liquibase:
    change-log: db/changelog/changelog-master.yml
    default-schema: public
    enabled: true
    password: db_bank_card
    user: db_bank_card

  datasource:
    url: jdbc:postgresql://localhost:5435/db_bank_card
    username: db_bank_card
    password: db_bank_card
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none
        globally_quoted_identifiers: true # ( user, order, group)
    generate-ddl: false
    show-sql: false

springdoc:
  swagger-ui:
    path: /ui

jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==

cooke:
  time:
    live:
      refreshToken: 86000